import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex flex-col min-h-screen bg-slate-900 text-white px-3 md:px-6`}
      >
        <header className="container mx-auto">Header</header>
        <main className="flex-1 container mx-auto">{children}</main>
        <footer className="container mx-auto">Footer</footer>
      </body>
    </html>
  );
}
